/*
 * Movie Renamer
 * Copyright (C) 2012 Nicolas Magré
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package fr.free.movierenamer.ui;

import fr.free.movierenamer.ui.res.ContextMenuFieldMouseListener;
import fr.free.movierenamer.utils.Utils;
import java.awt.Insets;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.ResourceBundle;
import javax.swing.DefaultListModel;
import javax.swing.GroupLayout;
import javax.swing.GroupLayout.Alignment;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTextField;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.WindowConstants;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 * Class Editor
 * @author Nicolas Magré
 */
public class Editor extends JDialog {

  private ArrayList<String> array;
  private DefaultListModel listModel;
  private String initValue;
  private ResourceBundle bundle = ResourceBundle.getBundle("fr/free/movierenamer/i18n/Bundle");

  /** Creates new form Editor
   * @param text
   * @param separator
   */
  public Editor(String text, String separator) {
    initComponents();
    initValue = text;
    array = new ArrayList<String>();
    String[] res = text.split(separator);
    if(!text.equals("")) array.addAll(Arrays.asList(res));
    listModel = new DefaultListModel();
    for (int i = 0; i < array.size(); i++) {
      listModel.addElement(array.get(i));
    }
    stringList.setModel(listModel);
    stringList.addListSelectionListener(new ListSelectionListener() {

      @Override
      public void valueChanged(ListSelectionEvent lse) {
        int index = stringList.getSelectedIndex();
        if (index != -1)
          stringField.setText(array.get(index));
        else stringField.setText("");
      }
    });

    if (array.size() > 0)
      stringList.setSelectedIndex(0);
    else {
      removeBtn.setEnabled(false);
      editBtn.setEnabled(false);
      stringField.setEnabled(false);
    }
    setTitle("Movie Renamer Editor");
    setLocationRelativeTo(getParent());
    setIconImage(Utils.getImageFromJAR("/image/icon-32.png", getClass()));
    setModal(true);
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jScrollPane1 = new JScrollPane();
    stringList = new JList();
    addBtn = new JButton();
    removeBtn = new JButton();
    stringField = new JTextField();
    editBtn = new JButton();
    cancelBtn = new JButton();
    okBtn = new JButton();

    setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);

    jScrollPane1.setViewportView(stringList);

    addBtn.setIcon(new ImageIcon(getClass().getResource("/image/list-add-5.png"))); // NOI18N
    ResourceBundle bundle = ResourceBundle.getBundle("fr/free/movierenamer/i18n/Bundle"); // NOI18N
    addBtn.setToolTipText(bundle.getString("add")); // NOI18N
    addBtn.addActionListener(new ActionListener() {
      public void actionPerformed(ActionEvent evt) {
        addBtnActionPerformed(evt);
      }
    });

    removeBtn.setIcon(new ImageIcon(getClass().getResource("/image/list-remove-4.png"))); // NOI18N
    removeBtn.setToolTipText(bundle.getString("removeFromList")); // NOI18N
    removeBtn.addActionListener(new ActionListener() {
      public void actionPerformed(ActionEvent evt) {
        removeBtnActionPerformed(evt);
      }
    });

    stringField.addMouseListener(new ContextMenuFieldMouseListener());

    editBtn.setIcon(new ImageIcon(getClass().getResource("/image/accessories-text-editor-6.png"))); // NOI18N
    editBtn.setToolTipText(bundle.getString("edit")); // NOI18N
    editBtn.addActionListener(new ActionListener() {
      public void actionPerformed(ActionEvent evt) {
        editBtnActionPerformed(evt);
      }
    });

    cancelBtn.setIcon(new ImageIcon(getClass().getResource("/image/dialog-cancel-2.png"))); // NOI18N
    cancelBtn.setText(bundle.getString("cancel")); // NOI18N
    cancelBtn.setToolTipText(bundle.getString("cancel")); // NOI18N
    cancelBtn.setMargin(new Insets(2, 2, 2, 2));
    cancelBtn.addActionListener(new ActionListener() {
      public void actionPerformed(ActionEvent evt) {
        cancelBtnActionPerformed(evt);
      }
    });

    okBtn.setIcon(new ImageIcon(getClass().getResource("/image/dialog-ok-2.png"))); // NOI18N
    okBtn.setText(bundle.getString("ok")); // NOI18N
    okBtn.setToolTipText(bundle.getString("ok")); // NOI18N
    okBtn.setMargin(new Insets(2, 2, 2, 2));
    okBtn.addActionListener(new ActionListener() {
      public void actionPerformed(ActionEvent evt) {
        okBtnActionPerformed(evt);
      }
    });

    GroupLayout layout = new GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(Alignment.LEADING)
          .addGroup(Alignment.TRAILING, layout.createSequentialGroup()
            .addComponent(okBtn, GroupLayout.PREFERRED_SIZE, 84, GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(ComponentPlacement.RELATED, 238, Short.MAX_VALUE)
            .addComponent(cancelBtn, GroupLayout.PREFERRED_SIZE, 84, GroupLayout.PREFERRED_SIZE))
          .addGroup(Alignment.TRAILING, layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(Alignment.LEADING)
              .addComponent(jScrollPane1, GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE)
              .addComponent(stringField, Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE))
            .addPreferredGap(ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(Alignment.LEADING)
              .addComponent(removeBtn, Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
              .addComponent(addBtn, Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
              .addComponent(editBtn, Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE))))
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addComponent(addBtn)
            .addPreferredGap(ComponentPlacement.UNRELATED)
            .addComponent(removeBtn))
          .addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 152, GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(ComponentPlacement.UNRELATED)
        .addGroup(layout.createParallelGroup(Alignment.TRAILING)
          .addComponent(stringField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
          .addComponent(editBtn))
        .addPreferredGap(ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
        .addGroup(layout.createParallelGroup(Alignment.BASELINE)
          .addComponent(cancelBtn, GroupLayout.PREFERRED_SIZE, 28, GroupLayout.PREFERRED_SIZE)
          .addComponent(okBtn, GroupLayout.PREFERRED_SIZE, 28, GroupLayout.PREFERRED_SIZE))
        .addContainerGap())
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void cancelBtnActionPerformed(ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
    dispose();
  }//GEN-LAST:event_cancelBtnActionPerformed

  private void editBtnActionPerformed(ActionEvent evt) {//GEN-FIRST:event_editBtnActionPerformed
    int index = stringList.getSelectedIndex();
    if (index != -1) {
      array.remove(index);
      array.add(index, stringField.getText());
      listModel.clear();
      for (int i = 0; i < array.size(); i++) {
        listModel.addElement(array.get(i));
      }
      stringList.setSelectedIndex(index);
    }
  }//GEN-LAST:event_editBtnActionPerformed

  private void addBtnActionPerformed(ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
    String s = (String) JOptionPane.showInputDialog(this, bundle.getString("add"), "Movie Renamer Editor", JOptionPane.PLAIN_MESSAGE);

    if ((s != null) && (s.length() > 0)) {
      array.add(s);
      listModel.addElement(s);
    }
  }//GEN-LAST:event_addBtnActionPerformed

  private void removeBtnActionPerformed(ActionEvent evt) {//GEN-FIRST:event_removeBtnActionPerformed
    int index = stringList.getSelectedIndex();
    if (index != -1) {
      array.remove(index);
      listModel.clear();
      for (int i = 0; i < array.size(); i++) {
        listModel.addElement(array.get(i));
      }
      if(index >= listModel.size()) index = listModel.size() - 1;
      stringField.setText("");
      stringList.setSelectedIndex(index);
    }
  }//GEN-LAST:event_removeBtnActionPerformed

  private void okBtnActionPerformed(ActionEvent evt) {//GEN-FIRST:event_okBtnActionPerformed
    String res = Utils.arrayToString(array, " | ", 0);
    if(!initValue.equals(res))
      firePropertyChange("", initValue, res);
    setVisible(false);
  }//GEN-LAST:event_okBtnActionPerformed

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private JButton addBtn;
  private JButton cancelBtn;
  private JButton editBtn;
  private JScrollPane jScrollPane1;
  private JButton okBtn;
  private JButton removeBtn;
  private JTextField stringField;
  private JList stringList;
  // End of variables declaration//GEN-END:variables
}
