/*
 * Movie Renamer
 * Copyright (C) 2014 Nicolas Magré
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package fr.free.movierenamer.ui.swing.dialog;

import com.alee.extended.label.WebLinkLabel;
import com.alee.extended.panel.GroupPanel;
import com.alee.laf.label.WebLabel;
import fr.free.movierenamer.ui.MovieRenamer;
import fr.free.movierenamer.ui.settings.UISettings;
import fr.free.movierenamer.ui.utils.ImageUtils;
import static fr.free.movierenamer.ui.utils.ImageUtils.getIcon;
import fr.free.movierenamer.ui.utils.UIUtils;
import static fr.free.movierenamer.ui.utils.UIUtils.i18n;
import java.awt.Dimension;
import java.net.URL;
import javax.swing.Icon;

/**
 * Class AboutDialog
 *
 * @author Nicolas Magré
 */
public class AboutDialog extends AbstractDialog {

  private static final Icon banner = getIcon((URL) null, new Dimension(505, 130), "ui/mr-ban.png");

  /**
   * Creates new form AboutDialog
   *
   * @param mr
   */
  public AboutDialog(MovieRenamer mr) {
    super(mr, i18n.getLanguage("toptb.about", true));
    initComponents();
    jScrollPane1.setViewportBorder(null);

    appnameLbl.setBoldFont();
    versionLbl.setBoldFont();
    authorLbl.setBoldFont();
    contributorLbl.setBoldFont();
    liscenseLbl.setBoldFont();
    providerLbl.setBoldFont();

    bannerLbl.setIcon(banner);
    appnameLbl.setLanguage(i18n.getLanguageKey("aboutDialog.appname", false), UISettings.APPNAME);
    versionLbl.setLanguage(i18n.getLanguageKey("aboutDialog.appversion", false), UISettings.VERSION);
    authorLbl.setText(i18n.getLanguage("aboutDialog.author", false, "\n-    " + UISettings.AUTHOR.replace("|", "\n-    ")));
    contributorLbl.setText(i18n.getLanguage("aboutDialog.contributor", false, UISettings.CONTRIB.replace("|", "\n-    ")));
    liscenseLbl.setLanguage(i18n.getLanguageKey("aboutDialog.license", false), UISettings.LICENSE);
    copyrightLbl.setLanguage(UISettings.COPYRIGHT);
    providerLbl.setLanguage(i18n.getLanguageKey("aboutDialog.provider", false));

    websiteLbl.setText(i18n.getLanguage("aboutDialog.website", false));
    websiteLbl.setLink(UISettings.HOST);

    for (String provider : UISettings.PROVIDER.split("\\|")) {
      WebLinkLabel wll = new WebLinkLabel();
      String[] vals = provider.split("\\s");
      if (vals.length != 2) {
        continue;
      }

      wll.setLink(vals[1]);
      webPanel1.add(new GroupPanel(4, new WebLabel(vals[0]), wll));
    }
    // TODO add contact

    pack();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    bannerLbl = new com.alee.laf.label.WebLabel();
    appnameLbl = new com.alee.laf.label.WebLabel();
    versionLbl = new com.alee.laf.label.WebLabel();
    authorLbl = new com.alee.extended.label.WebMultiLineLabel();
    contributorLbl = new com.alee.extended.label.WebMultiLineLabel();
    liscenseLbl = new com.alee.laf.label.WebLabel();
    copyrightLbl = new com.alee.laf.label.WebLabel();
    jScrollPane1 = new javax.swing.JScrollPane();
    webPanel1 = new com.alee.laf.panel.WebPanel();
    okBtn = UIUtils.createButton(i18n.getLanguageKey("ok", false), ImageUtils.OK_16);
    providerLbl = new com.alee.laf.label.WebLabel();
    websiteLbl = new com.alee.extended.label.WebLinkLabel();
    webLabel1 = new com.alee.laf.label.WebLabel();
    webLinkLabel1 = new com.alee.extended.label.WebLinkLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    setResizable(false);

    webPanel1.setLayout(new javax.swing.BoxLayout(webPanel1, javax.swing.BoxLayout.Y_AXIS));
    jScrollPane1.setViewportView(webPanel1);

    okBtn.setPreferredSize(UIUtils.buttonSize);
    okBtn.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        okBtnActionPerformed(evt);
      }
    });

    webLabel1.setText("Look and feel :  WebLaF");

    webLinkLabel1.setText("http://weblookandfeel.com/");

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(bannerLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 505, Short.MAX_VALUE)
          .addComponent(appnameLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(versionLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(authorLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
          .addComponent(contributorLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
          .addComponent(liscenseLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(providerLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(copyrightLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(websiteLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addGroup(layout.createSequentialGroup()
            .addComponent(okBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(0, 0, Short.MAX_VALUE))
          .addGroup(layout.createSequentialGroup()
            .addComponent(webLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(webLinkLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
          .addComponent(jScrollPane1))
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(bannerLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(18, 18, 18)
        .addComponent(appnameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(versionLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(authorLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(contributorLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(liscenseLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(providerLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(18, 18, 18)
        .addComponent(websiteLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(webLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(webLinkLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(18, 18, 18)
        .addComponent(copyrightLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(36, 36, 36)
        .addComponent(okBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap())
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void okBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okBtnActionPerformed
    dispose();
  }//GEN-LAST:event_okBtnActionPerformed

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private com.alee.laf.label.WebLabel appnameLbl;
  private com.alee.extended.label.WebMultiLineLabel authorLbl;
  private com.alee.laf.label.WebLabel bannerLbl;
  private com.alee.extended.label.WebMultiLineLabel contributorLbl;
  private com.alee.laf.label.WebLabel copyrightLbl;
  private javax.swing.JScrollPane jScrollPane1;
  private com.alee.laf.label.WebLabel liscenseLbl;
  private com.alee.laf.button.WebButton okBtn;
  private com.alee.laf.label.WebLabel providerLbl;
  private com.alee.laf.label.WebLabel versionLbl;
  private com.alee.laf.label.WebLabel webLabel1;
  private com.alee.extended.label.WebLinkLabel webLinkLabel1;
  private com.alee.laf.panel.WebPanel webPanel1;
  private com.alee.extended.label.WebLinkLabel websiteLbl;
  // End of variables declaration//GEN-END:variables
}
