/*
 * Movie_Renamer
 * Copyright (C) 2015 Nicolas Magré
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package fr.free.movierenamer.ui.swing.dialog;

import fr.free.movierenamer.ui.MovieRenamer;
import fr.free.movierenamer.ui.settings.UISettings;
import static fr.free.movierenamer.ui.utils.UIUtils.i18n;
import java.awt.Desktop;
import java.io.IOException;
import java.net.URISyntaxException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.event.HyperlinkEvent;
import javax.swing.event.HyperlinkListener;
import javax.swing.text.Document;
import javax.swing.text.html.HTMLEditorKit;
import javax.swing.text.html.StyleSheet;

/**
 *
 * @author Nicolas Magré
 */
public class AboutDialog extends AbstractDialog {

    /**
     * Creates new form NewJDialog
     */
    public AboutDialog(MovieRenamer mr) {
        super(mr, i18n.getLanguage("toptb.about", true));
        initComponents();
        HTMLEditorKit kit = new HTMLEditorKit();

        String p = getClass().getResource("/image/ui/mr-ban.png").toString();

        String html = "<html><body style=\"margin-left: 20px;margin-right: 20px;margin-top: 20px\">"
                + "<img src=\"" + p + "\" /><br><br>"
                + "<div style=\"text-align: center\">"
                + "    <p>" + UISettings.APPNAME + " " + UISettings.VERSION + " (Core : " + UISettings.CORE_VERSION + ")</p>"
                + "    <p><a href=\"http://www.movie-renamer.fr\">www.movie-renamer.fr</a></p></div><br>"
                + "<div style=\"text-align: justify;margin-left: 20px\">"
                + i18n.getLanguage("aboutDialog.author", false, "<ul style=\"list-style-type: none\"><li>" + UISettings.AUTHOR.replace("|", "</li><li>")) + "</li></ul>"
                + "</div>"
                + "<div style=\"text-align: justify;\">"
                + i18n.getLanguage("aboutDialog.provider", false) + "<ul style=\"list-style-type: none\"><li>" + UISettings.PROVIDER.replace("|", "</li><li>") + "</li></ul>"
                + "</div>"
                + "</body></html>";
        System.out.println(html);

        StyleSheet styleSheet = kit.getStyleSheet();
        styleSheet.addRule("");
        Document doc = kit.createDefaultDocument();
        webEditorPane1.setDocument(doc);
        webEditorPane1.setEditable(false);
        webEditorPane1.setEditorKit(kit);
        webEditorPane1.setText(html);
        webEditorPane1.addHyperlinkListener(new HyperlinkListener() {
            @Override
            public void hyperlinkUpdate(HyperlinkEvent e) {
                if (e.getEventType() == HyperlinkEvent.EventType.ACTIVATED) {
                    if (Desktop.isDesktopSupported()) {
                        try {
                            Desktop.getDesktop().browse(e.getURL().toURI());
                        } catch (IOException ex) {
                            Logger.getLogger(AboutDialog.class.getName()).log(Level.SEVERE, null, ex);
                        } catch (URISyntaxException ex) {
                            Logger.getLogger(AboutDialog.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }
                }
            }
        });

        pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        webEditorPane1 = new com.alee.laf.text.WebEditorPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jScrollPane1.setViewportView(webEditorPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private com.alee.laf.text.WebEditorPane webEditorPane1;
    // End of variables declaration//GEN-END:variables
}
