/*
 * Movie Renamer
 * Copyright (C) 2015 Nicolas Magré
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package fr.free.movierenamer.ui.swing.dialog;

import fr.free.movierenamer.ui.MovieRenamer;
import fr.free.movierenamer.ui.event.IEventListener;
import fr.free.movierenamer.ui.event.UIEvent;
import fr.free.movierenamer.ui.utils.ImageUtils;
import fr.free.movierenamer.ui.utils.UIUtils;
import static fr.free.movierenamer.ui.utils.UIUtils.i18n;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.ListModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 * Class ListEditor
 *
 * @author Nicolas Magré
 */
public abstract class ListEditor<T> extends AbstractDialog {

    private final DefaultListModel<Object> listModel = new DefaultListModel<>();
    private final List<Object> objectList;
    private final Class<? extends IEventListener> sendEventTo;

    public ListEditor(MovieRenamer mr, List<Object> objectList, Class<? extends IEventListener> sendEventTo) {
        this(mr, objectList, sendEventTo, true);
    }

    public ListEditor(MovieRenamer mr, List<Object> objectList, Class<? extends IEventListener> sendEventTo, boolean moveBtn) {
        super(mr, i18n.getLanguageKey("dialog.editor", false));
        this.objectList = objectList;
        this.sendEventTo = sendEventTo;
        initComponents();

        if (!moveBtn) {
            upBtn.setVisible(false);
            downBtn.setVisible(false);
        }

        list.setModel(listModel);
        list.addListSelectionListener(createListListener());

        for (Object obj : objectList) {
            listModel.addElement(obj.toString());
        }

        if (!listModel.isEmpty()) {
            list.setSelectedIndex(0);
        }
    }

    private ListSelectionListener createListListener() {
        return new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent lse) {
                int index = list.getSelectedIndex();
                if (!lse.getValueIsAdjusting()) {
                    removeBtn.setEnabled(index != -1);
                    upBtn.setEnabled(index > 0);
                    downBtn.setEnabled(listModel.size() > 1 && index != -1 && index != listModel.size() - 1);
                }
            }
        };
    }

    protected abstract T createNewValue();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        list = new com.alee.laf.list.WebList();
        addBtn = UIUtils.createButton(i18n.getLanguageKey("add", false), ImageUtils.PLUS_16);
        removeBtn = UIUtils.createButton(i18n.getLanguageKey("remove", false), ImageUtils.MINUS_16);
        upBtn = UIUtils.createButton(i18n.getLanguageKey("up", false), ImageUtils.UP_16);
        downBtn = UIUtils.createButton(i18n.getLanguageKey("down", false), ImageUtils.DOWN_16);
        applyBtn = UIUtils.createButton(i18n.getLanguageKey("apply", false), ImageUtils.OK_16);
        cancelBtn = UIUtils.createButton(i18n.getLanguageKey("cancel", false), ImageUtils.CANCEL_16);

        list.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(list);

        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        removeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeBtnActionPerformed(evt);
            }
        });

        upBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upBtnActionPerformed(evt);
            }
        });

        downBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                downBtnActionPerformed(evt);
            }
        });

        applyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                applyBtnActionPerformed(evt);
            }
        });

        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 349, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(removeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(upBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(downBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(applyBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(removeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(upBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(downBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(applyBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void upBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upBtnActionPerformed
        int index = list.getSelectedIndex();
        if (index > 0) {
            Object obj = listModel.get(index);
            listModel.remove(index);
            listModel.add(--index, obj);
            list.setSelectedIndex(index);
        }
    }//GEN-LAST:event_upBtnActionPerformed

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        dispose();
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void applyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_applyBtnActionPerformed
        List<Object> values = new ArrayList<>();
        ListModel model = list.getModel();
        int size = model.getSize();
        for (int i = 0; i < size; i++) {
            values.add(model.getElementAt(i));
        }

        UIEvent.fireUIEvent(UIEvent.Event.EDITED, sendEventTo, null, objectList, values);
        dispose();
    }//GEN-LAST:event_applyBtnActionPerformed

    private void downBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_downBtnActionPerformed
        int index = list.getSelectedIndex();
        if (index != -1 && index < listModel.size() - 1) {
            Object obj = listModel.get(index);
            listModel.remove(index);
            listModel.add(++index, obj);
            list.setSelectedIndex(index);
        }
    }//GEN-LAST:event_downBtnActionPerformed

    private void removeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeBtnActionPerformed
        int index = list.getSelectedIndex();
        if (index != -1) {
            listModel.remove(index);
            if (!listModel.isEmpty()) {
                list.setSelectedIndex(listModel.size() - 1 >= index ? index : index - 1);
            }
        }
    }//GEN-LAST:event_removeBtnActionPerformed

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        T obj = createNewValue();

        if (obj != null && !obj.toString().isEmpty()) {
            listModel.addElement(obj);
            if (list.getSelectedIndex() == -1) {
                list.setSelectedIndex(0);
            }
        }
    }//GEN-LAST:event_addBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.alee.laf.button.WebButton addBtn;
    private com.alee.laf.button.WebButton applyBtn;
    private com.alee.laf.button.WebButton cancelBtn;
    private com.alee.laf.button.WebButton downBtn;
    private javax.swing.JScrollPane jScrollPane1;
    private com.alee.laf.list.WebList list;
    private com.alee.laf.button.WebButton removeBtn;
    private com.alee.laf.button.WebButton upBtn;
    // End of variables declaration//GEN-END:variables
}
