/*
 * Movie Renamer
 * Copyright (C) 2012-2013 Nicolas Magré
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package fr.free.movierenamer.ui.swing.panel.info;

import fr.free.movierenamer.info.CastingInfo;
import fr.free.movierenamer.info.MovieInfo;
import fr.free.movierenamer.ui.bean.UIPersonImage;
import fr.free.movierenamer.ui.swing.ImageListModel;
import fr.free.movierenamer.ui.swing.renderer.CastingListRenderer;
import fr.free.movierenamer.ui.utils.ImageUtils;
import java.util.ArrayList;
import java.util.List;
import javax.swing.Icon;

/**
 * Class CastingInfoPane
 *
 * @author Nicolas Magré
 */
public class CastingInfoPanel<T extends MovieInfo> extends InfoPanel<T> {

  private T info;
  private final ImageListModel<UIPersonImage> directorListModel = new ImageListModel<>();
  private final ImageListModel<UIPersonImage> actorListModel = new ImageListModel<>();
  private final List<UIPersonImage> actorsList;
  private final List<UIPersonImage> directorsList;

  /**
   * Creates new form CastingInfoPanel
   */
  public CastingInfoPanel() {
    initComponents();
    actorsList = new ArrayList<>();
    directorsList = new ArrayList<>();

    directorList.setModel(directorListModel);
    actorList.setModel(actorListModel);
    directorList.setCellRenderer(new CastingListRenderer());
    actorList.setCellRenderer(new CastingListRenderer());
    directorList.setVisibleRowCount(0);
    actorList.setVisibleRowCount(0);
  }

  public ImageListModel<UIPersonImage> getDirectorListModel() {
    return directorListModel;
  }

  public ImageListModel<UIPersonImage> getActorListModel() {
    return actorListModel;
  }

  public List<UIPersonImage> getActors() {
    return actorsList;
  }

  public List<UIPersonImage> getDirectors() {
    return directorsList;
  }

  @Override
  public Icon getIcon() {
    return ImageUtils.CASTING_16;
  }

  @Override
  public String getPanelName() {
    return "casting";
  }

  @Override
  public void clear() {
    info = null;
    directorListModel.clear();
    actorListModel.clear();
    actorsList.clear();
    directorsList.clear();
  }

  @Override
  public void setInfo(T info) {
    this.info = info;
    UIPersonImage person;
    List<CastingInfo> cinfo = info.getActors();
    for (CastingInfo pinfo : cinfo) {
      person = new UIPersonImage(pinfo);
      actorsList.add(person);
    }
    actorListModel.addAll(actorsList);

    cinfo = info.getDirectors();
    for (CastingInfo pinfo : cinfo) {
      person = new UIPersonImage(pinfo);
      directorsList.add(person);
    }
    directorListModel.addAll(directorsList);
  }

  @Override
  public T getInfo() {
    return info;
  }

  @Override
  public PanelType getType() {
    return PanelType.CASTING_INFO;
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    directorTb = new com.alee.laf.toolbar.WebToolBar();
    directorLbl = new com.alee.laf.label.WebLabel();
    jScrollPane1 = new javax.swing.JScrollPane();
    directorList = new com.alee.laf.list.WebList();
    actorTb = new com.alee.laf.toolbar.WebToolBar();
    actorLbl = new com.alee.laf.label.WebLabel();
    jScrollPane2 = new javax.swing.JScrollPane();
    actorList = new com.alee.laf.list.WebList();

    directorTb.setFloatable(false);
    directorTb.setRollover(true);
    directorTb.setMargin(new java.awt.Insets(0, 4, 0, 4));
    directorTb.add(directorLbl);

    directorList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
    directorList.setLayoutOrientation(javax.swing.JList.HORIZONTAL_WRAP);
    jScrollPane1.setViewportView(directorList);

    actorTb.setFloatable(false);
    actorTb.setRollover(true);
    actorTb.setMargin(new java.awt.Insets(0, 4, 0, 4));
    actorTb.add(actorLbl);

    actorList.setLayoutOrientation(javax.swing.JList.HORIZONTAL_WRAP);
    jScrollPane2.setViewportView(actorList);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(directorTb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      .addComponent(actorTb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
          .addComponent(jScrollPane2))
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addComponent(directorTb, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(actorTb, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE))
    );
  }// </editor-fold>//GEN-END:initComponents
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private com.alee.laf.label.WebLabel actorLbl;
  private com.alee.laf.list.WebList actorList;
  private com.alee.laf.toolbar.WebToolBar actorTb;
  private com.alee.laf.label.WebLabel directorLbl;
  private com.alee.laf.list.WebList directorList;
  private com.alee.laf.toolbar.WebToolBar directorTb;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JScrollPane jScrollPane2;
  // End of variables declaration//GEN-END:variables

}
