/*
 * Copyright (C) 2013-2014 Nicolas Magré
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package fr.free.movierenamer.ui.swing.panel;

import com.alee.laf.panel.WebPanel;

/**
 * Class TaskPanel
 *
 * @author Nicolas Magré
 */
public class TaskPanel extends WebPanel {// TODO add status (pending, ....)
        
    public TaskPanel(String str) {
        this(str, true);
    }

    /**
     * Creates new form TaskPanel
     *
     * @param str
     * @param indeterminate
     */
    public TaskPanel(String str, boolean indeterminate) {
        initComponents();
        progressBar.setIndeterminate(indeterminate);
        progressBar.setMinimum(0);
        progressBar.setMaximum(100);
        nameLbl.setText(str);
    }
    
    public void setProgress(int progress) {
        if (progress < 0 || progress > 100) {
            progressBar.setIndeterminate(true);
            return;
        }
        progressBar.setIndeterminate(progress == 100);
        progressBar.setStringPainted(progress > 0);
        progressBar.setValue(progress);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nameLbl = new com.alee.laf.label.WebLabel();
        progressBar = new com.alee.laf.progressbar.WebProgressBar();

        setLayout(new java.awt.GridLayout());
        add(nameLbl);
        add(progressBar);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.alee.laf.label.WebLabel nameLbl;
    private com.alee.laf.progressbar.WebProgressBar progressBar;
    // End of variables declaration//GEN-END:variables
}
